server:
  port: ${PORT:8080}
  shutdown: graceful
  tomcat:
    connection-timeout: 10s
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
    threads:
      max: 200
      min-spare: 10
    keep-alive-timeout: 30s
    accept-count: 100
  address: 0.0.0.0

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  application:
    name: onboarding-app
  lifecycle:
    timeout-per-shutdown-phase: 60s
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      max-lifetime: 900000
      transaction-isolation: TRANSACTION_READ_COMMITTED
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 1024
        useServerPrepStmts: false
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
          batch_size: 15
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: false
          plan_cache_max_size: 4096
  config:
    import: optional:file:.env[.properties]